### ISSUE TITLE
How can I start MainActivity from any other activity?

### ISSUE THREAD

**Issue by activesince93** [kostasdrakonakis/flappybird#1]
Currently `MainActivity` is the launcher activity. But when I try to make any other activity let's say `LandingActivity` launcher activity and try to start `MainActivity` like below:

    val intent = Intent(applicationContext, MainActivity::class.java)
    startActivity(intent)

It is showing the black screen. Not starting the game. Is there any other way to do the same?

**Comment by kostasdrakonakis** [comment]
@activesince93 I have uploaded a demo using splash activity and starting MainActivity from it. Please clone project and build and check.

**Comment by activesince93** [comment]
Worked!
